stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - bash: |
          echo "Building model serving docker image"
          docker build -t codedaymodel.azurecr.io/codeday-model-serving -f model-serving/Dockerfile .
          echo "Building backend service docker image"
          docker build -t codedaymodel.azurecr.io/codeday-backend-service -f backend-service/Dockerfile .

  - stage: Test
    jobs:
      - job: TestJob
        steps:
          - bash: |
              echo "testing backend service..."
              echo "testing model-serving..."
  
  - stage: Deploy
    jobs:
      - job: 
        steps:
          - bash: |
              docker login codedaymodel.azurecr.io -u $(DOCEKR_USERNAME) -p $(DOCEKR_PASSWORD)
              docker push codedaymodel.azurecr.io/codeday-model-serving
              docker push codedaymodel.azurecr.io/codeday-backend-service
